version: '3.3'
services:

  unifi:
    build:
      context: ./docker-rpi
      dockerfile: ./dockerfile
    image: danielcoman/unifi-rpi:5.13.35
    environment:
      TZ: 'Europe/Bucharest'
      UNIFI_VERSION: '5.13.35'
