version: '3.3'
services:

  unifi:
    image: danielcoman/unifi:5.14.23
    build:
      context: ./docker
      dockerfile: ./dockerfile
      args:
        TZ: 'Europe/Bucharest'
        UNIFI_VERSION: '5.14.23'
