version: '3.3'
services:

  unifi:
    image: danielcoman/unifi-rpi:5.12.35
    command: ["start"]
    volumes:
      - config:/var/lib/unifi
    ports:
      - "3478:3478/udp"
      - "8080:8080/tcp"
      - "8443:8443/tcp"
      - "6789:6789/tcp"
      - "10001:10001/udp"
      - "1900:1900/udp"
    environment:
      TYPE: unifi
    networks:
      - unifi

volumes:
  config:

networks:
  unifi:
