FROM resin/rpi-raspbian:stretch


ENV DEBIAN_FRONTEND="noninteractive" TZ="Europe/Bucharest"

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update -y && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends unzip wget less && \
    rm -rf /var/lib/apt/lists/*
