FROM debian:stretch-slim

ARG TZ
ARG UNIFI_VERSION

RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone

RUN groupadd -r unifi && useradd -r -g unifi unifi

# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863199
RUN mkdir -p /usr/share/man/man1

RUN apt-get update && apt-get upgrade -y && \
    apt-get install --no-install-recommends -y openjdk-8-jdk jsvc mongodb-server wget binutils curl logrotate && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

RUN mkdir -p /tmp/build && \
    cd /tmp/build && \
    wget -q http://dl.ubnt.com/unifi/${UNIFI_VERSION}/unifi_sysvinit_all.deb && \
    dpkg --install unifi_sysvinit_all.deb && \
    rm -rf /tmp/build

WORKDIR /usr/lib/unifi

EXPOSE 3478/udp 8080/tcp 8443/tcp 6789/tcp 10001/udp 1900/udp

ENTRYPOINT ["/usr/bin/java", "-Xmx1024M", "-jar", "/usr/lib/unifi/lib/ace.jar"]
CMD ["start"]
